<script lang="ts">
 import Icon from "./StudioIcon.svelte";
 export let params:Record<string,number|boolean|number[]>;
 export let onchange:(key:string,value:number|boolean)=>void;
 export let onstart:()=>void;
 const modules=[{key:'cameraSmoke',name:'Smoke',icon:'smoke',hint:'Movement emits rising color'},{key:'cameraFluid',name:'Fluid',icon:'flux',hint:'Push and bend the live image'},{key:'cameraTrails',name:'Trails',icon:'trails',hint:'Leave luminous motion echoes'}];
 const sliders=[{key:'cameraSensitivity',name:'Motion sensitivity',value:.65,min:0,max:1},{key:'cameraEnergy',name:'Energy',value:1,min:.1,max:2.5},{key:'cameraMemory',name:'Persistence',value:.8,min:0,max:1},{key:'cameraOriginal',name:'Camera visibility',value:.65,min:0,max:1},{key:'cameraAmount',name:'FX mix',value:1,min:0,max:1},{key:'cameraAudio',name:'Audio push',value:0,min:0,max:2}];
 $: enabled=modules.some(m=>params[m.key]);
</script>
<section class="camera-fx" aria-label="Camera motion effects">
 <header><span>CAMERA MOTION FX</span><button onclick={()=>{onstart();onchange('cameraClear',Number(params.cameraClear??0)+1);}}>Clear trails</button></header>
 <div class="modules">{#each modules as m}<button class:active={!!params[m.key]} aria-pressed={!!params[m.key]} onclick={()=>{onstart();onchange(m.key,!params[m.key]);}}><span class="module-title"><Icon name={m.icon} size={19}/><strong>{m.name}</strong></span><small>{m.hint}</small></button>{/each}</div>
 <p>Move to generate. Combine effects; lower Camera visibility to perform with just the generated visuals.</p>
 {#if enabled}<div class="options"><label>Color<select aria-label="Camera FX color" value={Number(params.cameraPalette??0)} onchange={e=>onchange('cameraPalette',Number(e.currentTarget.value))}>{#each ['Glacier','Ember','Jade','Orchid','White','Camera colors'] as name,i}<option value={i}>{name}</option>{/each}</select></label><button class:active={!!params.cameraHold} aria-pressed={!!params.cameraHold} onclick={()=>onchange('cameraHold',!params.cameraHold)}>Hold motion</button></div>
 {#each sliders as s}{@const value=Number(params[s.key]??s.value)}<label class="slider"><span>{s.name}</span><input aria-label={s.name} type="range" min={s.min} max={s.max} step=".01" data-default={s.value} {value} style:--range-fill={(value-s.min)/(s.max-s.min)} onpointerdown={onstart} oninput={e=>onchange(s.key,Number(e.currentTarget.value))}/><output>{value.toFixed(2)}</output></label>{/each}
 {/if}
</section>
<style>
 .module-title{display:flex;align-items:center;gap:6px}
 .modules button.active:nth-child(1){border-color:#cb824b}.modules button.active:nth-child(1) .module-title{color:#ffb679}
 .modules button.active:nth-child(3){border-color:#77994e}.modules button.active:nth-child(3) .module-title{color:#b7f375}
 @media(max-width:600px){.slider{grid-template-columns:1fr auto!important;gap:0 8px!important;padding:4px 0!important}.slider span{grid-column:1;grid-row:1}.slider output{grid-column:2;grid-row:1}.slider input{grid-column:1/-1;grid-row:2}}

 .camera-fx{padding:14px;border:1px solid var(--ga-line-3);border-radius:7px;background:var(--ga-inspector-bg);margin:12px 0}header{display:flex;align-items:center;justify-content:space-between;gap:10px}header span{font-size:10px;letter-spacing:.1em;color:var(--ga-ink-2);font-weight:650}button,select{font:inherit;color:var(--ga-ink-0);background:var(--ga-hardware-bg);border:1px solid var(--ga-line-2);border-radius:5px;min-height:44px;padding:8px;touch-action:manipulation}header button{font-size:11px}.modules{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin:12px 0}.modules button{text-align:left;min-width:0;padding:12px 8px}.modules strong{font-size:13px;font-weight:650}.modules small{display:block;color:var(--ga-ink-2);font-size:10px;line-height:1.4;margin-top:5px}.active{background:var(--ga-selection-bg);border-color:var(--ga-selection-line);color:var(--ga-selection-ink)}p{font-size:11px;color:var(--ga-ink-2);line-height:1.5}.options{display:flex;align-items:end;gap:10px;margin:14px 0}.options label{flex:1;color:var(--ga-ink-2);font-size:11px}.options select{display:block;width:100%;margin-top:4px}.options button{font-size:12px}.slider{display:grid;grid-template-columns:105px minmax(0,1fr) 34px;gap:9px;align-items:center;min-height:48px;font-size:12px}.slider input{width:100%;min-width:0;height:40px;touch-action:pan-y}.slider input{-webkit-appearance:none;appearance:none;background:transparent}.slider input::-webkit-slider-runnable-track{height:8px;border:1px solid var(--ga-line-2);border-radius:3px;background:linear-gradient(90deg,var(--ga-blue-600) calc(var(--range-fill)*100%),var(--ga-slot) 0)}.slider input::-webkit-slider-thumb{-webkit-appearance:none;width:22px;height:28px;margin-top:-11px;border:1px solid var(--ga-line-3);border-radius:4px;background:var(--ga-hardware-bg);box-shadow:inset 0 -3px 0 var(--ga-blue-500)}.slider input::-moz-range-track{height:8px;background:var(--ga-slot)}.slider input::-moz-range-progress{height:8px;background:var(--ga-blue-600)}.slider input::-moz-range-thumb{width:22px;height:26px;border-radius:4px;border:1px solid var(--ga-line-3);background:var(--ga-hardware-bg)}.slider output{text-align:right;font:11px ui-monospace;color:var(--ga-ink-2)}
</style>
