<script lang="ts">
 import {onDestroy} from 'svelte';
 import {FLUX_MODULES,type FluxState} from '../../mobile/studio/flux';
 export let value:FluxState;
 export let onchange:(state:FluxState)=>void;
 let pointer:number|null=null;
 let expressionPointer:number|null=null;
 function energy(e:PointerEvent){const r=(e.currentTarget as HTMLElement).getBoundingClientRect();patch({energy:Math.max(0,Math.min(1,1-(e.clientY-r.top)/r.height))});}
 function lift(e:PointerEvent){if(e.pointerId===expressionPointer){expressionPointer=null;return;}if(e.pointerId===pointer)release();}
 const recipes=[{name:'Liquid prism',modules:['warp','prism']},{name:'Mirror maze',modules:['fold','echo']},{name:'Solar storm',modules:['solar','slice','warp']},{name:'All in',modules:FLUX_MODULES.map(m=>m.id)}];
 function patch(p:Partial<FluxState>){value={...value,...p};onchange(value);}
 function position(e:PointerEvent){const r=(e.currentTarget as HTMLElement).getBoundingClientRect();patch({x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,1-(e.clientY-r.top)/r.height)),active:true,...(e.pointerType==='pen'?{energy:e.pressure}: {})});}
 function down(e:PointerEvent){if(pointer!==null){if(expressionPointer===null){expressionPointer=e.pointerId;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);energy(e);}return;}e.preventDefault();pointer=e.pointerId;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);position(e);}
 function release(){pointer=null;expressionPointer=null;if(!value.latch)patch({active:false});}
 function reset(){pointer=null;expressionPointer=null;patch({active:false,latch:false});}
 function toggle(id:string){patch({modules:value.modules.includes(id)?value.modules.filter(m=>m!==id):[...value.modules,id]});}
 function key(e:KeyboardEvent){const d=.03;if(e.key==='Escape'){reset();return;}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();patch({x:Math.max(0,Math.min(1,value.x+(e.key==='ArrowRight'?d:e.key==='ArrowLeft'?-d:0))),y:Math.max(0,Math.min(1,value.y+(e.key==='ArrowUp'?d:e.key==='ArrowDown'?-d:0))),active:true});}
 onDestroy(()=>{if(!value.latch)onchange({...value,active:false});});
</script>
<div class="flux">
 <div class="heading"><div><span>PERFORMANCE INSTRUMENT</span><h1>Flux <i class:live={value.active&&value.modules.length>0}></i></h1></div><button class="reset" onclick={reset}>Release FX</button></div>
 <div class="tools"><button class:active={value.latch} aria-label="Flux stay on" aria-pressed={value.latch} onclick={()=>patch({latch:!value.latch,active:!value.latch || pointer!==null})}>{value.latch?'On':'Off'}</button><button class:active={value.beat} aria-pressed={value.beat} onclick={()=>patch({beat:!value.beat})}>Beat lock</button><select aria-label="Flux combination" value="" onchange={e=>{const r=recipes[Number(e.currentTarget.value)];if(r)patch({modules:[...r.modules]});e.currentTarget.value='';}}><option value="">Combinations</option>{#each recipes as r,i}<option value={i}>{r.name}</option>{/each}</select></div>
 <div class="instrument">
  <div class="pad" class:playing={value.active} role="application" aria-label="Flux XY pad. Horizontal changes character, vertical increases intensity. Arrow keys move; Escape releases." tabindex="0" onpointerdown={down} onpointermove={e=>{if(pointer===e.pointerId)position(e);else if(expressionPointer===e.pointerId)energy(e);}} onpointerup={lift} onpointercancel={lift} onlostpointercapture={lift} onkeydown={key} onkeyup={e=>{if(e.key.startsWith('Arrow')&&!value.latch)release();}} onblur={()=>{if(!value.latch)release();}}>
   <span class="axis top">WILD</span><span class="axis bottom">SUBTLE · CHARACTER →</span>
   <div class="cross-x" style={`left:${value.x*100}%`}></div><div class="cross-y" style={`bottom:${value.y*100}%`}></div><div class="cursor" style={`left:${value.x*100}%;bottom:${value.y*100}%`}></div>
   {#if !value.active}<span class="invitation">{value.modules.length?'Touch to play':'Choose a module →'}</span>{/if}
  </div>
  <div class="modules">{#each FLUX_MODULES as m}<button class:active={value.modules.includes(m.id)} aria-label={`Flux ${m.name}`} aria-pressed={value.modules.includes(m.id)} title={m.hint} onclick={()=>toggle(m.id)}>{m.name}</button>{/each}</div>
 </div>
 <label class="amount"><span>Wet / dry</span><input aria-label="Flux wet dry" type="range" min="0" max="1" step=".01" value={value.mix} oninput={e=>patch({mix:Number(e.currentTarget.value)})}/><output>{Math.round(value.mix*100)}%</output></label>
 <label class="amount"><span>Energy</span><input aria-label="Flux Energy" type="range" min="0" max="1" step=".01" value={value.energy||0} oninput={e=>patch({energy:Number(e.currentTarget.value)})}/><output>{Math.round((value.energy||0)*100)}%</output></label>
 <p>Pencil pressure or a second finger’s height adds Energy: deeper warp, zoom and color. Standard finger touches do not measure pressure.</p>
 <p>{value.latch?'On: keeps your last position when you lift your finger.':'Off: FX play only while you touch the pad.'} Stack modules with your other hand—each combination changes the gesture.</p>
</div>
<style>
 .heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.heading span{font-size:9px;letter-spacing:.12em;color:var(--ga-ink-2)}h1{margin:3px 0;font-size:23px;font-weight:600}i{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--ga-line-3);vertical-align:middle}i.live{background:var(--ga-green)}
 button,select{background:var(--ga-hardware-bg);border:1px solid var(--ga-line-2);border-radius:5px;color:var(--ga-ink-0);font:inherit;font-size:12px;min-height:42px;padding:4px 10px;touch-action:manipulation}.active{background:var(--ga-selection-bg);border-color:var(--ga-selection-line)}.reset{border-color:var(--ga-line-3)}.tools{display:flex;gap:6px;margin-bottom:10px}.tools select{flex:1;min-width:0}.instrument{display:grid;grid-template-columns:minmax(0,1fr) 78px;gap:8px}.pad{position:relative;height:286px;touch-action:none;user-select:none;overflow:hidden;border:1px solid var(--ga-line-3);border-radius:8px;background:radial-gradient(ellipse at 50% 80%,#17274b90,transparent 75%),repeating-linear-gradient(0deg,transparent 0 calc(25% - 1px),#ffffff09 calc(25% - 1px) 25%),repeating-linear-gradient(90deg,transparent 0 calc(25% - 1px),#ffffff09 calc(25% - 1px) 25%),var(--ga-slot)}.playing{border-color:var(--ga-selection-line);box-shadow:inset 0 0 45px #2145a633}.axis{position:absolute;left:10px;font-size:9px;letter-spacing:.1em;color:var(--ga-ink-2);pointer-events:none}.top{top:10px}.bottom{bottom:10px}.cross-x,.cross-y{position:absolute;background:#819eff3d;pointer-events:none}.cross-x{width:1px;top:0;bottom:0}.cross-y{height:1px;left:0;right:0}.cursor{position:absolute;width:26px;height:26px;border-radius:50%;border:2px solid #b5c9ff;background:#314b8faa;transform:translate(-50%,50%);box-shadow:0 0 0 8px #4063b51a;pointer-events:none}.playing .cursor{box-shadow:0 0 0 12px #4063b533,0 0 30px #4576df77}.invitation{position:absolute;inset:0;display:grid;place-items:center;font-size:12px;color:var(--ga-ink-1);pointer-events:none}.modules{display:grid;grid-template-rows:repeat(6,1fr);gap:5px}.modules button{padding:4px;min-height:42px}.amount{display:flex;align-items:center;gap:10px;font-size:11px;margin-top:8px}.amount input{flex:1;min-width:0;height:44px;accent-color:var(--ga-slider-fill);touch-action:none}.amount output{width:34px;text-align:right}p{font-size:11px;color:var(--ga-ink-2);line-height:1.5;margin:5px 0}.pad:focus-visible,button:focus-visible,select:focus-visible{outline:2px solid var(--ga-focus);outline-offset:2px}@media(max-width:760px){.heading{margin-bottom:6px;height:32px}.heading span{display:none}.heading button{min-height:32px}.pad{height:236px}.modules button{min-height:35px}.tools{margin-bottom:8px}.tools button,.tools select{min-height:36px}h1{font-size:20px;margin:0}p{font-size:10px}.amount{margin-top:2px}}
</style>
