import type {TextureInput} from './compositor';
export type CameraFxParams=Record<string,number|boolean|number[]>;
export const cameraFxEnabled=(p:CameraFxParams)=>!!(p.cameraSmoke||p.cameraFluid||p.cameraTrails);
const VERT=`attribute vec2 p;varying vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0,1);}`;
const COMMON=`precision highp float;varying vec2 uv;uniform sampler2D current,previous,history,flow,smoke,trails;uniform vec2 pixel;uniform float dt,time,sensitivity,memory,energy,palette,original,amount,smokeOn,fluidOn,trailsOn;
float luma(vec3 c){return dot(c,vec3(.299,.587,.114));}
vec2 velocity(vec2 p){return (texture2D(flow,p).rg*255.-128.)/127.;}
vec3 tint(float v){if(palette<.5)return mix(vec3(.06,.14,.65),vec3(.2,.85,1.),v);if(palette<1.5)return mix(vec3(.5,.015,.1),vec3(1.,.65,.1),v);if(palette<2.5)return mix(vec3(.05,.28,.22),vec3(.4,1.,.75),v);if(palette<3.5)return mix(vec3(.32,.04,.65),vec3(1.,.25,.7),v);if(palette<4.5)return vec3(.8+v*.2);return texture2D(current,uv).rgb;}
vec4 inside(sampler2D tex,vec2 p){if(min(p.x,p.y)<0.||max(p.x,p.y)>1.)return vec4(0.);return texture2D(tex,p);}`;
const FLOW=`${COMMON}void main(){vec3 c=texture2D(current,uv).rgb;float now=luma(c),old=luma(texture2D(previous,uv).rgb);vec2 grad=vec2(luma(texture2D(current,uv+vec2(pixel.x,0)).rgb)-luma(texture2D(current,uv-vec2(pixel.x,0)).rgb),luma(texture2D(current,uv+vec2(0,pixel.y)).rgb)-luma(texture2D(current,uv-vec2(0,pixel.y)).rgb));float change=length(c-texture2D(previous,uv).rgb);float motion=smoothstep(mix(.2,.015,sensitivity),mix(.6,.12,sensitivity),change);vec2 oldFlow=(texture2D(history,uv).rg*255.-128.)/127.;vec2 measured=clamp(-grad*(now-old)/(dot(grad,grad)+.015),-1.,1.);vec2 v=mix(oldFlow*exp(-dt*2.),measured,motion*.65);gl_FragColor=vec4((v*127.+128.)/255.,motion,1);}`;
const SMOKE=`${COMMON}void main(){vec2 v=velocity(uv);float m=texture2D(flow,uv).b;vec2 curl=vec2(sin(uv.y*22.+time*.6)+cos(uv.x*19.-time*.4),cos(uv.x*24.+time*.4)-sin(uv.y*17.+time*.5));vec2 p=uv-dt*(v*.35*energy+vec2(0,.055)+curl*.015*energy);vec4 h=inside(history,p)*.6;h+=(inside(history,p+vec2(pixel.x,0))+inside(history,p-vec2(pixel.x,0))+inside(history,p+vec2(0,pixel.y))+inside(history,p-vec2(0,pixel.y)))*.1;h=max(vec4(0),h*exp(-dt*mix(3.,.2,memory))-vec4(dt*.25));float injection=m*.5*energy;vec3 dye=tint(luma(texture2D(current,uv).rgb));gl_FragColor=vec4(min(vec3(1),h.rgb+dye*injection),min(1.,h.a+injection));}`;
const TRAILS=`${COMMON}void main(){vec2 v=velocity(uv);vec2 p=(uv-.5)*(1.-dt*.05*energy)+.5-v*dt*.12*energy;vec4 h=max(vec4(0),inside(history,p)*exp(-dt*mix(5.,.18,memory))-vec4(dt*.25));float m=texture2D(flow,uv).b;vec3 c=texture2D(current,uv).rgb;float a=m*min(1.,energy);gl_FragColor=vec4(max(h.rgb,c*a),max(h.a,a));}`;
const COMPOSE=`${COMMON}void main(){vec2 v=velocity(uv);vec2 warp=v*.09*energy*fluidOn;vec4 c=inside(current,uv-warp);if(fluidOn>.5){c.r=inside(current,uv-warp*1.25).r;c.b=inside(current,uv-warp*.75).b;}vec4 s=texture2D(smoke,uv)*smokeOn,t=texture2D(trails,uv)*trailsOn;vec3 emitted=1.-(1.-s.rgb)*(1.-t.rgb);float a=max(s.a,t.a);float cameraAlpha=c.a*original;float outA=cameraAlpha+a*(1.-cameraAlpha);vec3 rgb=(c.rgb*cameraAlpha*(1.-a*.45)+emitted)/max(.001,outA);vec4 effect=vec4(clamp(rgb,0.,1.),outA);gl_FragColor=mix(texture2D(current,uv),effect,amount);}`;
const COPY=`precision highp float;varying vec2 uv;uniform sampler2D current;void main(){gl_FragColor=texture2D(current,uv);}`;
type Target=TextureInput&{fbo:WebGLFramebuffer};
/** Motion is measured and advected entirely in the shared GPU context; history never leaves the GPU. */
export class CameraFx {
 private programs:WebGLProgram[]=[];private locations=new Map<WebGLProgram,Map<string,WebGLUniformLocation|null>>();private quad:WebGLBuffer;
 private targets:Target[]=[];private index=0;private lastTime=0;private clearToken=-1;private primed=false;private held=false;
 constructor(private gl:WebGLRenderingContext){this.quad=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,this.quad);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);try{for(const code of [FLOW,SMOKE,TRAILS,COMPOSE,COPY])this.programs.push(this.compile(code));}catch(e){this.destroy();throw e;}}
 private compile(fragment:string){const g=this.gl,p=g.createProgram()!,shaders:WebGLShader[]=[];try{for(const [type,code] of [[g.VERTEX_SHADER,VERT],[g.FRAGMENT_SHADER,fragment]] as const){const s=g.createShader(type)!;shaders.push(s);g.shaderSource(s,code);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(s)||'Camera FX shader failed.');g.attachShader(p,s);}g.bindAttribLocation(p,0,'p');g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p)||'Camera FX program failed.');return p;}catch(e){g.deleteProgram(p);throw e;}finally{shaders.forEach(s=>g.deleteShader(s));}}
 private loc(p:WebGLProgram,name:string){let map=this.locations.get(p);if(!map){map=new Map();this.locations.set(p,map);}if(!map.has(name))map.set(name,this.gl.getUniformLocation(p,name));return map.get(name)!;}
 private target(width:number,height:number):Target{const g=this.gl,texture=g.createTexture()!,fbo=g.createFramebuffer()!;g.bindTexture(g.TEXTURE_2D,texture);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,width,height,0,g.RGBA,g.UNSIGNED_BYTE,null);g.bindFramebuffer(g.FRAMEBUFFER,fbo);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,texture,0);if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE){g.deleteTexture(texture);g.deleteFramebuffer(fbo);throw new Error('Camera FX memory unavailable.');}return{texture,fbo,width,height};}
 private disposeTargets(){for(const t of this.targets){this.gl.deleteTexture(t.texture);this.gl.deleteFramebuffer(t.fbo);}this.targets=[];}
 private clear(){const g=this.gl;g.disable(g.SCISSOR_TEST);for(let i=0;i<this.targets.length;i++){g.bindFramebuffer(g.FRAMEBUFFER,this.targets[i].fbo);g.clearColor(i<2?128/255:0,i<2?128/255:0,0,i<2?1:0);g.clear(g.COLOR_BUFFER_BIT);}this.primed=false;}
 private pass(index:number,target:Target,inputs:Record<string,TextureInput>,uniforms:Record<string,number>){const g=this.gl,p=this.programs[index];g.bindFramebuffer(g.FRAMEBUFFER,target.fbo);g.viewport(0,0,target.width,target.height);g.disable(g.BLEND);g.disable(g.DEPTH_TEST);g.disable(g.SCISSOR_TEST);g.useProgram(p);g.bindBuffer(g.ARRAY_BUFFER,this.quad);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,2,g.FLOAT,false,0,0);let unit=0;for(const [name,t] of Object.entries(inputs)){g.activeTexture(g.TEXTURE0+unit);g.bindTexture(g.TEXTURE_2D,t.texture);g.uniform1i(this.loc(p,name),unit++);}for(const [name,value] of Object.entries(uniforms))g.uniform1f(this.loc(p,name),value);g.uniform2f(this.loc(p,'pixel'),1/this.targets[0].width,1/this.targets[0].height);g.drawArrays(g.TRIANGLES,0,6);}
 process(source:TextureInput,params:CameraFxParams,time:number,advance=true,audio=0):TextureInput{
  const value=(key:string,fallback:number)=>typeof params[key]==='number'?Math.max(0,Math.min(5,params[key] as number)):fallback;
  if(!this.targets.length||this.targets[7].width!==source.width||this.targets[7].height!==source.height){this.disposeTargets();const scale=Math.min(1,320/Math.max(source.width,source.height)),w=Math.max(2,Math.round(source.width*scale)),h=Math.max(2,Math.round(source.height*scale));for(let i=0;i<7;i++)this.targets.push(this.target(w,h));this.targets.push(this.target(source.width,source.height));this.clear();}
  const reset=Number(params.cameraClear??0);if(reset!==this.clearToken){this.clear();this.clearToken=reset;}
  const hold=params.cameraHold===true||!advance;
  if(!this.primed||this.held&&!hold||time-this.lastTime>.3){this.pass(4,this.targets[6],{current:source},{});this.primed=true;}
  const uniforms={dt:Math.min(.05,Math.max(.001,time-this.lastTime)),time,sensitivity:value('cameraSensitivity',.65),memory:value('cameraMemory',.8),energy:value('cameraEnergy',1)+audio*value('cameraAudio',0),palette:value('cameraPalette',0),original:value('cameraOriginal',.65),amount:value('cameraAmount',1),smokeOn:params.cameraSmoke?1:0,fluidOn:params.cameraFluid?1:0,trailsOn:params.cameraTrails?1:0};
  const next=1-this.index;
  if(!hold){this.pass(0,this.targets[next],{current:source,previous:this.targets[6],history:this.targets[this.index]},uniforms);
   if(params.cameraSmoke)this.pass(1,this.targets[2+next],{current:source,flow:this.targets[next],history:this.targets[2+this.index]},uniforms);
   if(params.cameraTrails)this.pass(2,this.targets[4+next],{current:source,flow:this.targets[next],history:this.targets[4+this.index]},uniforms);
   this.index=next;this.pass(4,this.targets[6],{current:source},{});
  }
  this.pass(3,this.targets[7],{current:source,flow:this.targets[this.index],smoke:this.targets[2+this.index],trails:this.targets[4+this.index]},uniforms);
  this.lastTime=time;this.held=hold;return this.targets[7];
 }
 destroy(){this.disposeTargets();this.programs.forEach(p=>this.gl.deleteProgram(p));this.programs=[];this.gl.deleteBuffer(this.quad);this.locations.clear();}
}
