// Arena preset — indoor venue with a centred ice / floor layout, a
// massive curved video wall behind the artist, and two side IMAG walls.
// Slightly more wrapped than Festival because indoor audiences sit
// closer; the curve hugs the eye-line.

import type { Stage3DScene } from '../types';

export const ARENA_PRESET: Stage3DScene = {
  id: 'preset-arena',
  name: 'Arena',
  schemaVersion: 1,
  environment: {
    background: '#020308',
    ambient: 0.25,
    showGround: true,
    groundColor: '#08080c',
  },
  camera: {
    position: [0, 6, 20],
    target: [0, 3, 0],
    fov: 55,
  },
  platform: {
    enabled: true,
    position: [0, 0, -2],
    width: 18,
    height: 1.0,
    depth: 7,
    topColor: '#08080c',
    skirtColor: '#15141a',
    underglow: { enabled: true, color: '#69F0AE', intensity: 1.4 },
    bevelSize: 0.15,
  },
  nodes: [
    // Massive curved hero wall.
    {
      id: 'arena-hero',
      name: 'Hero Wall',
      type: 'led-screen',
      position: [0, 5.5, -6],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 24,
      height: 8,
      curvature: -0.04,
      finish: 'led',
      frameDepth: 0.35,
      source: 'auto',
      brightness: 1.7,
      showPixels: false,
    },
    // Side IMAG portrait screens, angled toward the audience.
    {
      id: 'arena-imag-l',
      name: 'IMAG Left',
      type: 'led-screen',
      position: [-12, 5, -4],
      rotation: [0, Math.PI / 6, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 4,
      height: 6,
      curvature: 0,
      finish: 'led',
      frameDepth: 0.3,
      source: 'auto',
      brightness: 1.55,
      showPixels: false,
    },
    {
      id: 'arena-imag-r',
      name: 'IMAG Right',
      type: 'led-screen',
      position: [12, 5, -4],
      rotation: [0, -Math.PI / 6, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 4,
      height: 6,
      curvature: 0,
      finish: 'led',
      frameDepth: 0.3,
      source: 'auto',
      brightness: 1.55,
      showPixels: false,
    },
    // Stage-front LED ribbons — sit on the deck top, angled slightly
    // upward toward the audience.
    {
      id: 'arena-ribbon-l',
      name: 'Stage Ribbon Left',
      type: 'led-screen',
      position: [-5, 1.45, 1.2],
      rotation: [Math.PI / 16, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 6,
      height: 1.0,
      curvature: 0,
      finish: 'led',
      frameDepth: 0.15,
      source: 'auto',
      brightness: 1.3,
      showPixels: false,
    },
    {
      id: 'arena-ribbon-r',
      name: 'Stage Ribbon Right',
      type: 'led-screen',
      position: [5, 1.45, 1.2],
      rotation: [Math.PI / 16, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 6,
      height: 1.0,
      curvature: 0,
      finish: 'led',
      frameDepth: 0.15,
      source: 'auto',
      brightness: 1.3,
      showPixels: false,
    },
    // Drum riser cube — small portrait screen behind kit, hi-bright.
    {
      id: 'arena-riser',
      name: 'Riser Screen',
      type: 'led-screen',
      position: [0, 1.5, -3.5],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 3,
      height: 2,
      curvature: 0,
      finish: 'led',
      frameDepth: 0.2,
      source: 'auto',
      brightness: 1.8,
      showPixels: false,
    },
  ],
  lightingCueId: null,
  meta: { category: 'indoor', scale: 'large' },
};
