// Club preset — intimate dancefloor with the DJ booth as a screen-clad
// fortress and a low-ceiling backdrop. Camera lands in the middle of
// the dancefloor looking at the booth. Tight curvature on the booth so
// it wraps the DJ.

import type { Stage3DScene } from '../types';

export const CLUB_PRESET: Stage3DScene = {
  id: 'preset-club',
  name: 'Club Dancefloor',
  schemaVersion: 1,
  environment: {
    background: '#05030a',
    ambient: 0.18,
    showGround: true,
    groundColor: '#15101d',
  },
  camera: {
    position: [0, 2.4, 9],
    target: [0, 2, -1],
    fov: 60,
  },
  platform: {
    enabled: true,
    position: [0, 0, -1.8],
    width: 8,
    height: 0.6,
    depth: 3.5,
    topColor: '#0a0810',
    skirtColor: '#1a1424',
    underglow: { enabled: true, color: '#BB86FC', intensity: 2.4 },
    bevelSize: 0.1,
  },
  nodes: [
    // Booth front — wraps the DJ, deep curve.
    {
      id: 'club-booth-front',
      name: 'Booth Wrap',
      type: 'led-screen',
      position: [0, 1.6, -2],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 7,
      height: 1.5,
      curvature: -0.12,
      finish: 'led',
      frameDepth: 0.25,
      source: 'auto',
      brightness: 2.0,
      showPixels: true,
    },
    // Booth backdrop — taller wall behind DJ.
    {
      id: 'club-back',
      name: 'Booth Backdrop',
      type: 'led-screen',
      position: [0, 3, -4],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 8,
      height: 3,
      curvature: -0.04,
      finish: 'led',
      frameDepth: 0.3,
      source: 'auto',
      brightness: 1.7,
      showPixels: false,
    },
    // Ceiling strip — runs above the booth toward the dancefloor.
    {
      id: 'club-ceiling-strip',
      name: 'Ceiling Strip',
      type: 'led-screen',
      position: [0, 4.4, 1],
      rotation: [Math.PI / 2.3, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 8,
      height: 1.2,
      curvature: 0,
      finish: 'led',
      frameDepth: 0.15,
      source: 'auto',
      brightness: 1.3,
      showPixels: false,
    },
    // Side pillar — left.
    {
      id: 'club-pillar-l',
      name: 'Side Pillar Left',
      type: 'led-screen',
      position: [-5.5, 2.5, 0],
      rotation: [0, Math.PI / 4, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 1.4,
      height: 4.5,
      curvature: 0,
      finish: 'led',
      frameDepth: 0.2,
      source: 'auto',
      brightness: 1.4,
      showPixels: true,
    },
    {
      id: 'club-pillar-r',
      name: 'Side Pillar Right',
      type: 'led-screen',
      position: [5.5, 2.5, 0],
      rotation: [0, -Math.PI / 4, 0],
      scale: [1, 1, 1],
      visible: true,
      width: 1.4,
      height: 4.5,
      curvature: 0,
      finish: 'led',
      frameDepth: 0.2,
      source: 'auto',
      brightness: 1.4,
      showPixels: true,
    },
  ],
  lightingCueId: null,
  meta: { category: 'indoor', scale: 'small' },
};
