import assert from 'node:assert/strict';import {build} from 'esbuild';
const result=await build({entryPoints:['src/lib/mobile/studio/interactive.ts'],bundle:true,write:false,format:'esm',platform:'node'});const {defaultInteractive,defaultMatter,validateScene,inside,collision,InteractiveWorld,MotionSensor}=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
// validateScene fills in the Matter settings a scene does not carry, and is stable when run again.
const scene=defaultInteractive();const valid=validateScene(scene);assert.deepEqual(valid,{...scene,matter:defaultMatter()});assert.deepEqual(validateScene(valid),valid);assert.throws(()=>validateScene({...scene,energy:NaN}));assert.throws(()=>validateScene({...scene,surfaces:[{...scene.surfaces[0],points:[{x:Infinity,y:0}]}]}));assert.throws(()=>validateScene({...scene,surfaces:[scene.surfaces[0],scene.surfaces[0]]}));
assert.ok(inside({x:.25,y:.5},scene.surfaces[0].points));assert.ok(!inside({x:.9,y:.9},scene.surfaces[0].points));const hit=collision({x:0,y:.5},{x:1,y:.5},{x:.4,y:0},{x:.4,y:1});assert.equal(hit.t,.4);assert.equal(collision({x:0,y:0},{x:1,y:0},{x:0,y:1},{x:1,y:1}),null);
const w=new InteractiveWorld();w.particles=[{x:.14,y:.5,vx:.5,vy:0,life:10,seed:0}];w.update({...scene,gravity:0},.05,[]);assert.ok(w.particles[0].vx<0);assert.ok(w.particles[0].x<.15);
const input={id:'touch',point:{x:.7,y:.5},strength:1};w.update(scene,.05,[input]);assert.equal(w.pulses.length,1);for(let i=0;i<20;i++)w.update(scene,.05,[input]);assert.equal(w.pulses.length,1,'Held touch must not retrigger');w.update(scene,.05,[]);w.update(scene,.05,[input]);assert.equal(w.pulses.length,2);
for(let i=0;i<10000;i++)w.update(scene,.05,[input]);/* The particle bound is the world's quality budget (600 points by default), no longer a fixed 350. */const cap=w.qualityDiagnostics().pointLimit;assert.ok(cap>0&&cap<=600,'default point budget');assert.ok(w.particles.length<=cap);assert.ok(w.particles.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));assert.ok(w.pulses.length<=20);
const sensor=new MotionSensor(),black=new Uint8ClampedArray(64*36*4),patch=black.slice();assert.equal(sensor.sample(black,64,36,.5).length,0);for(let y=12;y<20;y++)for(let x=40;x<48;x++){const i=(y*64+x)*4;patch[i]=patch[i+1]=patch[i+2]=255;}const motion=sensor.sample(patch,64,36,.5);assert.equal(motion.length,1);assert.ok(motion[0].point.x>.6);assert.equal(sensor.sample(patch,64,36,.5).length,0);assert.equal(sensor.sample(new Uint8ClampedArray(64*36*4).fill(255),64,36,.5).length,0,'Global lighting change must be rejected');
console.log('PASS scene validation, polygon hit test, swept wall collision, trigger entry/debounce, bounded long simulation, localized motion and global-light rejection');
